# These keywords are arguments to run_experiment.main
base:
  initial_batch_size: [64]
  lr: [0.0025]
  dataset: [synthetic]
  tuning: [False]
  test_freq: [0.5]
sgd: {}
adagrad: {}
cntsdamplr:
  dampingfactor: [0.10]
geodamplr:
  dampingdelay: [8]
  dampingfactor: [2]
adadamp:
  initial_batch_size: [2]
  test_freq: [0.1]
gd: {}
